SELECT P.ID,
    CASE
        WHEN P.PER <= 0.25 THEN 'CRITICAL'
        WHEN P.PER <= 0.5 THEN 'HIGH'
        WHEN P.PER <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS 'COLONY_NAME'
FROM (
    SELECT
        ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PER
    FROM
        ECOLI_DATA) AS P
ORDER BY
    P.ID