WITH APPOINTMENT_FILTERED AS (
    SELECT 
        APNT_NO, PT_NO, MCDP_CD, MDDR_ID, APNT_YMD
    FROM 
        APPOINTMENT
    WHERE 
        APNT_YMD LIKE '2022-04-13%' 
        AND APNT_CNCL_YN = 'N'
        AND MCDP_CD = 'CS'
)

SELECT 
    A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM 
    APPOINTMENT_FILTERED A
    JOIN PATIENT P ON A.PT_NO = P.PT_NO
    JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
ORDER BY 
    A.APNT_YMD ASC;