SELECT
    YEAR(ED.DIFFERENTIATION_DATE) AS YEAR,
    MAX_SIZE - ED.SIZE_OF_COLONY AS YEAR_DEV,
    ED.ID
FROM
    ECOLI_DATA AS ED
JOIN (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM
        ECOLI_DATA
    GROUP BY
        YEAR(DIFFERENTIATION_DATE)
) AS MAX_COLONY
ON YEAR(ED.DIFFERENTIATION_DATE) = MAX_COLONY.YEAR
ORDER BY
    YEAR, YEAR_DEV;
