SELECT 
    CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM 
    FOOD_PRODUCT F
WHERE 
    CATEGORY IN ('과자', '국', '김치', '식용유')
    AND PRICE = (
        SELECT MAX(PRICE)
        FROM FOOD_PRODUCT S
        WHERE S.CATEGORY = F.CATEGORY
    )
ORDER BY 
    MAX_PRICE DESC;
