WITH L AS (
    SELECT
        ID, FISH_TYPE, IFNULL(LENGTH, 10) AS LEN
    FROM 
        FISH_INFO
)

SELECT
    COUNT(*) AS FISH_COUNT, MAX(LEN) AS MAX_LENGTH, FISH_TYPE
FROM
    L
GROUP BY
    FISH_TYPE
HAVING
    AVG(LEN) >= 33
ORDER BY
    FISH_TYPE;